language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-27.0.3                # Build tools version
    - android-27                        # Target SDK version

before_install:
  - yes | sdkmanager "platforms;android-27"

jdk:
  - oraclejdk8

script:
  - ./gradlew build

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle